/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import javax.swing.JLabel;

/**
 *
 * @author Felipe Ramirez
 */
public class Simulacion extends javax.swing.JFrame {

    /**
     * Creates new form Simulacion
     */
    public Simulacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        }
     public JLabel getcarro2(){
        return carro2;
     }
     public JLabel getcarro4(){
         return carro4;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carro4 = new javax.swing.JLabel();
        carro2 = new javax.swing.JLabel();
        semaforo4 = new javax.swing.JPanel();
        verde4 = new javax.swing.JPanel();
        naranja4 = new javax.swing.JPanel();
        rojo4 = new javax.swing.JPanel();
        semaforo2 = new javax.swing.JPanel();
        rojo2 = new javax.swing.JPanel();
        naranja2 = new javax.swing.JPanel();
        verde2 = new javax.swing.JPanel();
        semaforo1 = new javax.swing.JPanel();
        verde1 = new javax.swing.JPanel();
        naranja1 = new javax.swing.JPanel();
        rojo1 = new javax.swing.JPanel();
        semaforo3 = new javax.swing.JPanel();
        rojo3 = new javax.swing.JPanel();
        naranja3 = new javax.swing.JPanel();
        verde3 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        empezar = new javax.swing.JButton();
        fondop3 = new javax.swing.JPanel();
        projo3 = new javax.swing.JPanel();
        pverde3 = new javax.swing.JPanel();
        fondop1 = new javax.swing.JPanel();
        projo1 = new javax.swing.JPanel();
        pverde1 = new javax.swing.JPanel();
        fondop2 = new javax.swing.JPanel();
        projo2 = new javax.swing.JPanel();
        pverde2 = new javax.swing.JPanel();
        fondop4 = new javax.swing.JPanel();
        projo4 = new javax.swing.JPanel();
        pverde4 = new javax.swing.JPanel();
        carro3 = new javax.swing.JLabel();
        carro6 = new javax.swing.JLabel();
        carro7 = new javax.swing.JLabel();
        carro5 = new javax.swing.JLabel();
        carro12 = new javax.swing.JLabel();
        carro9 = new javax.swing.JLabel();
        carro10 = new javax.swing.JLabel();
        carro11 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro4.png"))); // NOI18N
        getContentPane().add(carro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, 20));

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro2.png"))); // NOI18N
        getContentPane().add(carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        semaforo4.setBackground(new java.awt.Color(0, 0, 0));
        semaforo4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout verde4Layout = new javax.swing.GroupLayout(verde4);
        verde4.setLayout(verde4Layout);
        verde4Layout.setHorizontalGroup(
            verde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        verde4Layout.setVerticalGroup(
            verde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout naranja4Layout = new javax.swing.GroupLayout(naranja4);
        naranja4.setLayout(naranja4Layout);
        naranja4Layout.setHorizontalGroup(
            naranja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        naranja4Layout.setVerticalGroup(
            naranja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rojo4Layout = new javax.swing.GroupLayout(rojo4);
        rojo4.setLayout(rojo4Layout);
        rojo4Layout.setHorizontalGroup(
            rojo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rojo4Layout.setVerticalGroup(
            rojo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout semaforo4Layout = new javax.swing.GroupLayout(semaforo4);
        semaforo4.setLayout(semaforo4Layout);
        semaforo4Layout.setHorizontalGroup(
            semaforo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rojo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naranja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        semaforo4Layout.setVerticalGroup(
            semaforo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semaforo4Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(semaforo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naranja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rojo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(semaforo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        semaforo2.setBackground(new java.awt.Color(0, 0, 0));
        semaforo2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout rojo2Layout = new javax.swing.GroupLayout(rojo2);
        rojo2.setLayout(rojo2Layout);
        rojo2Layout.setHorizontalGroup(
            rojo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rojo2Layout.setVerticalGroup(
            rojo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout naranja2Layout = new javax.swing.GroupLayout(naranja2);
        naranja2.setLayout(naranja2Layout);
        naranja2Layout.setHorizontalGroup(
            naranja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        naranja2Layout.setVerticalGroup(
            naranja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout verde2Layout = new javax.swing.GroupLayout(verde2);
        verde2.setLayout(verde2Layout);
        verde2Layout.setHorizontalGroup(
            verde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        verde2Layout.setVerticalGroup(
            verde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout semaforo2Layout = new javax.swing.GroupLayout(semaforo2);
        semaforo2.setLayout(semaforo2Layout);
        semaforo2Layout.setHorizontalGroup(
            semaforo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naranja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        semaforo2Layout.setVerticalGroup(
            semaforo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semaforo2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(semaforo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naranja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(semaforo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        semaforo1.setBackground(new java.awt.Color(0, 0, 0));
        semaforo1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout verde1Layout = new javax.swing.GroupLayout(verde1);
        verde1.setLayout(verde1Layout);
        verde1Layout.setHorizontalGroup(
            verde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        verde1Layout.setVerticalGroup(
            verde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout naranja1Layout = new javax.swing.GroupLayout(naranja1);
        naranja1.setLayout(naranja1Layout);
        naranja1Layout.setHorizontalGroup(
            naranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        naranja1Layout.setVerticalGroup(
            naranja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rojo1Layout = new javax.swing.GroupLayout(rojo1);
        rojo1.setLayout(rojo1Layout);
        rojo1Layout.setHorizontalGroup(
            rojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rojo1Layout.setVerticalGroup(
            rojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout semaforo1Layout = new javax.swing.GroupLayout(semaforo1);
        semaforo1.setLayout(semaforo1Layout);
        semaforo1Layout.setHorizontalGroup(
            semaforo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semaforo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naranja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        semaforo1Layout.setVerticalGroup(
            semaforo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naranja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(semaforo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        semaforo3.setBackground(new java.awt.Color(0, 0, 0));
        semaforo3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout rojo3Layout = new javax.swing.GroupLayout(rojo3);
        rojo3.setLayout(rojo3Layout);
        rojo3Layout.setHorizontalGroup(
            rojo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rojo3Layout.setVerticalGroup(
            rojo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout naranja3Layout = new javax.swing.GroupLayout(naranja3);
        naranja3.setLayout(naranja3Layout);
        naranja3Layout.setHorizontalGroup(
            naranja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        naranja3Layout.setVerticalGroup(
            naranja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout verde3Layout = new javax.swing.GroupLayout(verde3);
        verde3.setLayout(verde3Layout);
        verde3Layout.setHorizontalGroup(
            verde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        verde3Layout.setVerticalGroup(
            verde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout semaforo3Layout = new javax.swing.GroupLayout(semaforo3);
        semaforo3.setLayout(semaforo3Layout);
        semaforo3Layout.setHorizontalGroup(
            semaforo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semaforo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semaforo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(naranja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        semaforo3Layout.setVerticalGroup(
            semaforo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naranja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(semaforo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 204, 0));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, -1, -1));

        empezar.setText("EMPEZAR");
        empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarActionPerformed(evt);
            }
        });
        getContentPane().add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 150, 70));

        fondop3.setBackground(new java.awt.Color(255, 255, 0));

        projo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout projo3Layout = new javax.swing.GroupLayout(projo3);
        projo3.setLayout(projo3Layout);
        projo3Layout.setHorizontalGroup(
            projo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        projo3Layout.setVerticalGroup(
            projo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pverde3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pverde3.setPreferredSize(new java.awt.Dimension(13, 12));

        javax.swing.GroupLayout pverde3Layout = new javax.swing.GroupLayout(pverde3);
        pverde3.setLayout(pverde3Layout);
        pverde3Layout.setHorizontalGroup(
            pverde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pverde3Layout.setVerticalGroup(
            pverde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondop3Layout = new javax.swing.GroupLayout(fondop3);
        fondop3.setLayout(fondop3Layout);
        fondop3Layout.setHorizontalGroup(
            fondop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondop3Layout.setVerticalGroup(
            fondop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop3Layout.createSequentialGroup()
                .addComponent(pverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(fondop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 30, 30));

        fondop1.setBackground(new java.awt.Color(255, 255, 0));

        projo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout projo1Layout = new javax.swing.GroupLayout(projo1);
        projo1.setLayout(projo1Layout);
        projo1Layout.setHorizontalGroup(
            projo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        projo1Layout.setVerticalGroup(
            projo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pverde1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pverde1.setPreferredSize(new java.awt.Dimension(13, 12));

        javax.swing.GroupLayout pverde1Layout = new javax.swing.GroupLayout(pverde1);
        pverde1.setLayout(pverde1Layout);
        pverde1Layout.setHorizontalGroup(
            pverde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pverde1Layout.setVerticalGroup(
            pverde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondop1Layout = new javax.swing.GroupLayout(fondop1);
        fondop1.setLayout(fondop1Layout);
        fondop1Layout.setHorizontalGroup(
            fondop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondop1Layout.setVerticalGroup(
            fondop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop1Layout.createSequentialGroup()
                .addComponent(pverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(fondop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 30, 30));

        fondop2.setBackground(new java.awt.Color(255, 255, 51));

        projo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout projo2Layout = new javax.swing.GroupLayout(projo2);
        projo2.setLayout(projo2Layout);
        projo2Layout.setHorizontalGroup(
            projo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        projo2Layout.setVerticalGroup(
            projo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pverde2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pverde2.setPreferredSize(new java.awt.Dimension(13, 12));

        javax.swing.GroupLayout pverde2Layout = new javax.swing.GroupLayout(pverde2);
        pverde2.setLayout(pverde2Layout);
        pverde2Layout.setHorizontalGroup(
            pverde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pverde2Layout.setVerticalGroup(
            pverde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondop2Layout = new javax.swing.GroupLayout(fondop2);
        fondop2.setLayout(fondop2Layout);
        fondop2Layout.setHorizontalGroup(
            fondop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondop2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fondop2Layout.setVerticalGroup(
            fondop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondop2Layout.createSequentialGroup()
                .addComponent(pverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(fondop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 30, 30));

        fondop4.setBackground(new java.awt.Color(255, 255, 0));

        projo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout projo4Layout = new javax.swing.GroupLayout(projo4);
        projo4.setLayout(projo4Layout);
        projo4Layout.setHorizontalGroup(
            projo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        projo4Layout.setVerticalGroup(
            projo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pverde4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pverde4.setPreferredSize(new java.awt.Dimension(13, 12));

        javax.swing.GroupLayout pverde4Layout = new javax.swing.GroupLayout(pverde4);
        pverde4.setLayout(pverde4Layout);
        pverde4Layout.setHorizontalGroup(
            pverde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        pverde4Layout.setVerticalGroup(
            pverde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondop4Layout = new javax.swing.GroupLayout(fondop4);
        fondop4.setLayout(fondop4Layout);
        fondop4Layout.setHorizontalGroup(
            fondop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondop4Layout.setVerticalGroup(
            fondop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondop4Layout.createSequentialGroup()
                .addComponent(pverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(fondop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 30, 30));

        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro1.png"))); // NOI18N
        getContentPane().add(carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        carro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro6.png"))); // NOI18N
        getContentPane().add(carro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 750, -1, -1));
        carro6.getAccessibleContext().setAccessibleName("carro6");

        carro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro7.png"))); // NOI18N
        getContentPane().add(carro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 750, -1, -1));
        carro7.getAccessibleContext().setAccessibleName("carro7");

        carro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro5.png"))); // NOI18N
        getContentPane().add(carro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        carro12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro12.png"))); // NOI18N
        getContentPane().add(carro12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        carro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro9.png"))); // NOI18N
        getContentPane().add(carro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 260, -1, -1));

        carro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro10.png"))); // NOI18N
        getContentPane().add(carro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 310, -1, -1));

        carro11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro11.png"))); // NOI18N
        carro11.setToolTipText("");
        getContentPane().add(carro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 350, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo7.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarActionPerformed
       
        Carro hilo1=new Carro(carro2, this);
        Carro hilo2=new Carro(carro4, this);
      
       hilo1.start();
       hilo2.start();
       //hilo3.start();
       //hilo4.start();
        proceso objeto = new proceso(rojo1,naranja1,verde1,rojo3,naranja3,verde3,rojo2,naranja2,verde2,rojo4,naranja4,verde4,pverde1,pverde2,pverde3,pverde4,projo1,projo2,projo3,projo4,carro2,carro4);
        objeto.start();
       
        //hilo3.start();
            // TODO add your handling code here:
    }//GEN-LAST:event_empezarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {
         /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacion().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carro10;
    private javax.swing.JLabel carro11;
    private javax.swing.JLabel carro12;
    private javax.swing.JLabel carro2;
    private javax.swing.JLabel carro3;
    private javax.swing.JLabel carro4;
    private javax.swing.JLabel carro5;
    private javax.swing.JLabel carro6;
    private javax.swing.JLabel carro7;
    private javax.swing.JLabel carro9;
    private javax.swing.JButton empezar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondop1;
    private javax.swing.JPanel fondop2;
    private javax.swing.JPanel fondop3;
    private javax.swing.JPanel fondop4;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel naranja1;
    private javax.swing.JPanel naranja2;
    private javax.swing.JPanel naranja3;
    private javax.swing.JPanel naranja4;
    private javax.swing.JPanel projo1;
    private javax.swing.JPanel projo2;
    private javax.swing.JPanel projo3;
    private javax.swing.JPanel projo4;
    private javax.swing.JPanel pverde1;
    private javax.swing.JPanel pverde2;
    private javax.swing.JPanel pverde3;
    private javax.swing.JPanel pverde4;
    private javax.swing.JPanel rojo1;
    private javax.swing.JPanel rojo2;
    private javax.swing.JPanel rojo3;
    private javax.swing.JPanel rojo4;
    private javax.swing.JPanel semaforo1;
    private javax.swing.JPanel semaforo2;
    private javax.swing.JPanel semaforo3;
    private javax.swing.JPanel semaforo4;
    private javax.swing.JPanel verde1;
    private javax.swing.JPanel verde2;
    private javax.swing.JPanel verde3;
    private javax.swing.JPanel verde4;
    // End of variables declaration//GEN-END:variables
}
